# Generated by Django 5.2.4 on 2025-07-19 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="available",
            name="status",
            field=models.CharField(
                choices=[("Added", "Added"), ("Not Added", "Not Added")],
                default="REJECTED",
                max_length=20,
                null=True,
            ),
        ),
    ]
