# Generated by Django 5.2.4 on 2025-07-20 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_available_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="available",
            name="status",
            field=models.CharField(
                choices=[("ADDED", "ADDED"), ("REJECTED", "REJECTED")],
                default="REJECTED",
                max_length=20,
                null=True,
            ),
        ),
    ]
