# Generated by Django 5.2.3 on 2025-07-06 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="complaint",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("working on", "Working on"),
                    ("resolved", "Resolved"),
                ],
                default="pending",
                max_length=20,
                null=True,
            ),
        ),
    ]
