# Generated by Django 5.2.3 on 2025-07-07 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_alter_complaint_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="feedback",
            old_name="shopid",
            new_name="userid",
        ),
        migrations.RemoveField(
            model_name="complaint",
            name="shopid",
        ),
        migrations.AddField(
            model_name="feedback",
            name="productid",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.product",
            ),
        ),
    ]
