# Generated by Django 5.2.4 on 2025-07-20 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_alter_available_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="available",
            name="status",
            field=models.CharField(
                choices=[("ADDED", "ADDED"), ("Not Added", "Not Added")],
                default="Not Added",
                max_length=20,
                null=True,
            ),
        ),
    ]
