# Generated by Django 5.2.4 on 2025-07-29 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_category_rename_productid_order_productcate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="quantityAvailable",
            field=models.IntegerField(default=0),
        ),
    ]
