# Generated by Django 5.2.4 on 2025-07-29 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_order_quantityavailable"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="quantityAvailable",
        ),
        migrations.AddField(
            model_name="shopproduct",
            name="quantityAvailable",
            field=models.IntegerField(default=0),
        ),
    ]
