# Generated by Django 5.2.4 on 2025-07-29 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_remove_order_quantityavailable_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="productcate",
            new_name="productid",
        ),
        migrations.AddField(
            model_name="shopproduct",
            name="productcate",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.category",
            ),
        ),
    ]
