# Generated by Django 5.2.4 on 2025-07-29 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0008_rename_productcate_order_productid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="fed",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.feedback",
            ),
        ),
    ]
