# Generated by Django 5.2.4 on 2025-07-29 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0009_order_fed"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="fed",
        ),
        migrations.AddField(
            model_name="feedback",
            name="fed",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.order",
            ),
        ),
    ]
