# Generated by Django 5.2.4 on 2025-07-29 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0010_remove_order_fed_feedback_fed"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feedback",
            name="fed",
        ),
    ]
