# Generated by Django 5.2.4 on 2025-07-29 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0011_remove_feedback_fed"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="fed",
            field=models.BooleanField(default=False),
        ),
    ]
