# Generated by Django 5.2.4 on 2025-07-29 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0012_order_fed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="fed",
            field=models.IntegerField(default=1),
        ),
    ]
