# Generated by Django 5.2.4 on 2025-07-29 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0013_alter_order_fed"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="orderid",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.order",
            ),
        ),
    ]
