# Generated by Django 5.2.4 on 2025-07-30 04:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0015_cart"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="stat",
        ),
        migrations.AddField(
            model_name="cart",
            name="color",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="cart",
            name="image",
            field=models.ImageField(null=True, upload_to="product/"),
        ),
        migrations.AddField(
            model_name="cart",
            name="model",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="cart",
            name="price",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="cart",
            name="productcate",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.category",
            ),
        ),
        migrations.AddField(
            model_name="cart",
            name="productname",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="cart",
            name="quantityAvailable",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="cart",
            name="shopid",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="cart",
            name="productid",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.product",
            ),
        ),
    ]
