# Generated by Django 5.2.4 on 2025-07-30 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0016_remove_cart_stat_cart_color_cart_image_cart_model_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="color",
        ),
        migrations.RemoveField(
            model_name="cart",
            name="image",
        ),
        migrations.RemoveField(
            model_name="cart",
            name="model",
        ),
        migrations.RemoveField(
            model_name="cart",
            name="price",
        ),
        migrations.RemoveField(
            model_name="cart",
            name="productcate",
        ),
        migrations.RemoveField(
            model_name="cart",
            name="productname",
        ),
        migrations.AlterField(
            model_name="cart",
            name="productid",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.shopproduct",
            ),
        ),
    ]
