# Generated by Django 5.2.4 on 2025-07-31 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0017_remove_cart_color_remove_cart_image_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, null=True)),
                ("cardnumber", models.IntegerField(null=True)),
                ("cvv", models.IntegerField(null=True)),
                ("orderdate", models.DateTimeField(null=True)),
            ],
        ),
    ]
