# Generated by Django 5.2.4 on 2025-07-31 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0018_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="method",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
