# Generated by Django 5.2.4 on 2025-07-31 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0019_payment_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="orderid",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.order",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="productid",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.shopproduct",
            ),
        ),
    ]
